name: Build and Deploy React App

on:
  push:
    paths:
      - 'react/**'
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: Fix esbuild version issue
        run: |
          cd react
          # Create or update package.json to include resolutions for esbuild
          if [ -f "package.json" ]; then
            # Check if we're using yarn
            if [ -f "yarn.lock" ]; then
              # Add resolutions field if it doesn't exist
              if ! grep -q "resolutions" package.json; then
                sed -i 's/{"name":/{"resolutions": {"esbuild": "0.25.0"},"name":/' package.json
              elif ! grep -q "esbuild" package.json; then
                sed -i 's/"resolutions": {/"resolutions": {"esbuild": "0.25.0",/' package.json
              fi
            else
              # For npm, we'll use overrides
              if ! grep -q "overrides" package.json; then
                sed -i 's/{"name":/{"overrides": {"esbuild": "0.25.0"},"name":/' package.json
              elif ! grep -q "esbuild" package.json; then
                sed -i 's/"overrides": {/"overrides": {"esbuild": "0.25.0",/' package.json
              fi
            fi
          fi
          
      - name: Install dependencies
        run: |
          cd react
          # Force clear cache before installing
          rm -rf node_modules/.cache
          # Use --force to ensure all dependencies are correctly installed with proper versions
          npm install --force
          
      - name: Build React app
        run: |
          cd react
          # Set NODE_OPTIONS to increase memory limit if needed
          export NODE_OPTIONS=--max_old_space_size=4096
          npm run build
          
      - name: Backup any custom files
        run: |
          # Create backup of any custom-named files (like searchpage.html)
          mkdir -p temp_backup
          if [ -f "searchpage.html" ]; then
            cp searchpage.html temp_backup/
          fi
          # Add any other custom files you want to preserve here
          
      - name: Deploy to repository
        run: |
          # Remove old dist files (if they exist)
          rm -rf dist
          
          # Move the new build files to the correct location
          # This assumes your React app's build output is in 'react/dist'
          mv react/dist ./
          
          # Restore any custom files from backup
          if [ -f "temp_backup/searchpage.html" ]; then
            # If index.html should be renamed to searchpage.html
            if [ -f "dist/index.html" ] && [ ! -f "dist/searchpage.html" ]; then
              mv dist/index.html dist/searchpage.html
            # Or if we should keep a separate copy
            elif [ -f "dist/index.html" ]; then
              cp temp_backup/searchpage.html dist/
            fi
          fi
          
          # Clean up the backup
          rm -rf temp_backup
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add dist
          git commit -m "Update built React app" || echo "No changes to commit"
          git push
