name: Generate Sitemap with Action

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Generate sitemap.xml
      uses: cicirello/generate-sitemap@v1.10.0  # Explicit latest version
      with:
        base-url: 'https://v1.sefgh.org'        # ✅ no trailing slash

    - name: Commit sitemap  
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add sitemap.xml
        git commit -m "Auto-generate sitemap.xml" || echo "No changes to commit"
        git push
